-- =====================================================================
-- App Evolua — base de alimentos (por 100 g). Gerado por
-- ferramentas/gerar_base_alimentos.py — não editar à mão.
-- O app consulta esta base ANTES de chamar a IA; o que a IA descobrir de
-- novo é gravado aqui (fonte = 'ia') e fica disponível pra próxima vez.
-- Rodar no SQL Editor do Supabase. Pode rodar de novo: atualiza a base TACO
-- sem apagar o que a IA aprendeu.
-- =====================================================================
create table if not exists fit_alimentos (
  id bigint generated always as identity primary key,
  nome text not null unique,
  chaves text[] not null default '{}',
  kcal numeric not null,
  p numeric not null default 0,
  c numeric not null default 0,
  g numeric not null default 0,
  porcao numeric not null default 100,
  unidade text not null default 'porção',
  fonte text not null default 'taco',
  criado_por uuid default auth.uid(),
  criado_em timestamptz not null default now()
);

alter table fit_alimentos enable row level security;
drop policy if exists "ler alimentos" on fit_alimentos;
drop policy if exists "ia ensina alimento" on fit_alimentos;
create policy "ler alimentos" on fit_alimentos for select to anon, authenticated using (true);
-- usuários logados só podem ACRESCENTAR itens aprendidos pela IA (não alteram a base TACO)
create policy "ia ensina alimento" on fit_alimentos for insert to authenticated with check (fonte = 'ia');

insert into fit_alimentos (nome, chaves, kcal, p, c, g, porcao, unidade, fonte) values
  ('Arroz branco cozido', array['arroz','arroz branco','arroz branco cozido']::text[], 128, 2.5, 28.1, 0.2, 150, 'escumadeira cheia', 'taco'),
  ('Arroz integral cozido', array['arroz integral','arroz integral cozido']::text[], 124, 2.6, 25.8, 1.0, 150, 'escumadeira cheia', 'taco'),
  ('Arroz com feijão (mistura)', array['arroz com feijao','arroz e feijao misturado','arroz com feijao (mistura)']::text[], 110, 3.6, 21, 0.4, 250, 'prato', 'taco'),
  ('Macarrão cozido', array['penne','massa','parafuso','macarrao','talharim','espaguete','macarrao cozido']::text[], 158, 5.8, 30.9, 0.9, 200, 'prato raso', 'taco'),
  ('Macarrão integral cozido', array['macarrao integral','macarrao integral cozido']::text[], 124, 5.3, 26.5, 0.5, 200, 'prato raso', 'taco'),
  ('Lasanha à bolonhesa', array['lasanha','lasanha a bolonhesa']::text[], 160, 8.5, 14, 7.8, 300, 'pedaço', 'taco'),
  ('Macarrão instantâneo (preparado)', array['miojo','lamen','macarrao instantaneo','macarrao instantaneo (preparado)']::text[], 190, 4, 26, 7.5, 250, 'pacote preparado', 'taco'),
  ('Nhoque ao sugo', array['nhoque','nhoque ao sugo']::text[], 140, 3, 26, 2.5, 250, 'prato', 'taco'),
  ('Pão francês', array['pao','paozinho','pao de sal','pao frances']::text[], 300, 8.0, 58.6, 3.1, 50, 'unidade', 'taco'),
  ('Pão de forma', array['pao de forma','pao de sanduiche']::text[], 253, 12, 44, 2.7, 25, 'fatia', 'taco'),
  ('Pão de forma integral', array['pao integral','pao de forma integral']::text[], 253, 9.4, 49.9, 3.7, 25, 'fatia', 'taco'),
  ('Pão de queijo', array['pao de queijo']::text[], 363, 5.1, 34.2, 24.6, 40, 'unidade média', 'taco'),
  ('Pão sírio / árabe', array['pao pita','pao arabe','pao sirio','pao sirio / arabe']::text[], 275, 9, 55, 1.2, 60, 'unidade', 'taco'),
  ('Pão de hambúrguer', array['pao de hamburger','pao de hamburguer']::text[], 270, 8.5, 49, 4.3, 60, 'unidade', 'taco'),
  ('Pão doce / bisnaguinha', array['pao doce','bisnaguinha','pao de leite','pao doce / bisnaguinha']::text[], 310, 8.4, 55, 6, 20, 'unidade', 'taco'),
  ('Torrada', array['torrada','torradas']::text[], 400, 11, 75, 6, 10, 'unidade', 'taco'),
  ('Bolacha de água e sal / cream cracker', array['agua e sal','cream cracker','bolacha de agua e sal','bolacha de agua e sal / cream cracker']::text[], 432, 10.1, 68.7, 14.4, 6, 'unidade', 'taco'),
  ('Biscoito maisena / maria', array['maisena','bolacha maria','biscoito maria','biscoito maisena / maria']::text[], 443, 8.1, 75.2, 12, 5, 'unidade', 'taco'),
  ('Biscoito recheado', array['oreo','negresco','passatempo','bolacha recheada','biscoito recheado']::text[], 472, 5.5, 70.5, 19.6, 12, 'unidade', 'taco'),
  ('Biscoito de polvilho', array['polvilho','biscoito de polvilho']::text[], 438, 1.3, 75, 14, 3, 'unidade', 'taco'),
  ('Tapioca (goma)', array['tapioca','tapioca (goma)','goma de tapioca']::text[], 240, 0, 60, 0, 60, 'unidade média', 'taco'),
  ('Cuscuz de milho cozido', array['cuscuz','cuscuz nordestino','cuscuz de milho cozido']::text[], 113, 2.2, 25.3, 0.7, 150, 'fatia/porção', 'taco'),
  ('Farofa pronta', array['farofa','farofa pronta']::text[], 406, 2.1, 80.3, 9.1, 20, 'colher de sopa cheia', 'taco'),
  ('Farinha de mandioca', array['farinha','farinha de mandioca']::text[], 361, 1.6, 87.9, 0.3, 15, 'colher de sopa', 'taco'),
  ('Aveia em flocos', array['aveia','aveia em flocos']::text[], 394, 13.9, 66.6, 8.5, 30, '3 colheres de sopa', 'taco'),
  ('Granola', array['granola']::text[], 420, 9, 66, 14, 40, 'porção', 'taco'),
  ('Cereal matinal açucarado', array['cereal','sucrilhos','nescau cereal','cereal matinal','cereal matinal acucarado']::text[], 380, 5, 85, 2, 30, 'porção', 'taco'),
  ('Milho verde cozido/lata', array['milho','milho verde','milho verde cozido/lata']::text[], 98, 3.2, 17.1, 2.4, 60, '3 colheres de sopa', 'taco'),
  ('Pipoca (com óleo)', array['pipoca','pipoca (com oleo)']::text[], 448, 9.9, 70.3, 15.9, 25, 'saquinho pequeno', 'taco'),
  ('Pipoca de micro-ondas', array['pipoca de microondas','pipoca de micro-ondas']::text[], 480, 8, 55, 25, 50, 'meio pacote', 'taco'),
  ('Panqueca de carne', array['panqueca','panqueca de carne']::text[], 190, 9, 18, 9, 120, 'unidade', 'taco'),
  ('Crepioca', array['crepioca']::text[], 190, 9, 22, 7, 100, 'unidade', 'taco'),
  ('Waffle / panqueca americana', array['waffle','pancake','panqueca americana','waffle / panqueca americana']::text[], 290, 7, 38, 12, 60, 'unidade', 'taco'),
  ('Batata inglesa cozida', array['batata','batata cozida','batata inglesa cozida']::text[], 52, 1.2, 11.9, 0.1, 150, 'unidade média', 'taco'),
  ('Purê de batata', array['pure','pure de batata']::text[], 110, 2, 15, 4.5, 150, 'porção', 'taco'),
  ('Batata frita', array['fritas','batata frita']::text[], 312, 3.4, 41, 15, 120, 'porção pequena', 'taco'),
  ('Batata palha', array['batata palha']::text[], 540, 6, 52, 35, 25, 'porção', 'taco'),
  ('Batata-doce cozida', array['batata doce','batata-doce','batata-doce cozida']::text[], 77, 0.6, 18.4, 0.1, 150, 'unidade média', 'taco'),
  ('Mandioca cozida', array['aipim','mandioca','macaxeira','mandioca cozida']::text[], 125, 0.6, 30.1, 0.3, 150, 'pedaço', 'taco'),
  ('Mandioca frita', array['aipim frito','mandioca frita']::text[], 300, 1.4, 50, 11, 120, 'porção', 'taco'),
  ('Inhame / cará cozido', array['cara','inhame','inhame / cara cozido']::text[], 97, 2, 23, 0.2, 150, 'unidade', 'taco'),
  ('Mandioquinha cozida', array['batata baroa','mandioquinha','mandioquinha cozida']::text[], 80, 0.9, 18.9, 0.2, 120, 'unidade', 'taco'),
  ('Feijão carioca cozido', array['feijao','feijao carioca','caldo de feijao','feijao carioca cozido']::text[], 76, 4.8, 13.6, 0.5, 140, 'concha', 'taco'),
  ('Feijão preto cozido', array['feijao preto','feijao preto cozido']::text[], 77, 4.5, 14, 0.5, 140, 'concha', 'taco'),
  ('Feijoada', array['feijoada']::text[], 117, 8.7, 11.6, 6.5, 250, 'concha grande', 'taco'),
  ('Feijão tropeiro', array['tropeiro','feijao tropeiro']::text[], 152, 10.2, 19.6, 6.8, 150, 'porção', 'taco'),
  ('Lentilha cozida', array['lentilha','lentilha cozida']::text[], 93, 6.3, 16.3, 0.5, 130, 'concha', 'taco'),
  ('Grão-de-bico cozido', array['grao-de-bico','grao de bico','grao-de-bico cozido']::text[], 164, 8.9, 27.4, 2.6, 100, 'porção', 'taco'),
  ('Ervilha cozida', array['ervilha','ervilha cozida']::text[], 88, 7.5, 14.2, 0.5, 60, '3 colheres de sopa', 'taco'),
  ('Soja cozida', array['soja','soja cozida']::text[], 173, 16.6, 9.9, 9, 100, 'porção', 'taco'),
  ('Proteína de soja (PTS) hidratada', array['pts','carne de soja','proteina de soja','proteina de soja (pts) hidratada']::text[], 108, 16, 9, 0.3, 100, 'porção', 'taco'),
  ('Tofu', array['tofu']::text[], 76, 8, 1.9, 4.8, 100, 'porção', 'taco'),
  ('Homus', array['homus','hummus']::text[], 177, 8, 20, 9.6, 30, '2 colheres de sopa', 'taco'),
  ('Peito de frango grelhado', array['frango','sassami','file de frango','frango grelhado','peito de frango','peito de frango grelhado']::text[], 159, 32, 0, 2.5, 120, 'filé', 'taco'),
  ('Frango desfiado', array['frango desfiado']::text[], 163, 31, 0, 3.5, 100, 'porção', 'taco'),
  ('Coxa/sobrecoxa de frango assada', array['coxa','sobrecoxa','coxa de frango','coxa/sobrecoxa de frango assada']::text[], 215, 27, 0, 11.7, 100, 'unidade', 'taco'),
  ('Frango frito (empanado)', array['nugget','nuggets','frango frito','frango empanado','frango frito (empanado)']::text[], 280, 17, 14, 17, 100, 'porção', 'taco'),
  ('Coração de frango', array['coracao','coracaozinho','coracao de frango']::text[], 207, 22.4, 0, 12.1, 100, 'espeto/porção', 'taco'),
  ('Patinho grelhado', array['bife','carne','patinho','carne vermelha','patinho grelhado']::text[], 219, 35.9, 0, 7.3, 120, 'bife', 'taco'),
  ('Carne moída refogada', array['moida','carne moida','carne moida refogada']::text[], 212, 26.7, 0, 10.9, 100, 'porção', 'taco'),
  ('Alcatra grelhada', array['alcatra','maminha','contrafile','file mignon','contra file','alcatra grelhada']::text[], 241, 31.9, 0, 11.6, 150, 'bife', 'taco'),
  ('Picanha grelhada', array['picanha','picanha grelhada']::text[], 289, 26.4, 0, 19.5, 150, 'fatia grande', 'taco'),
  ('Costela bovina assada', array['costela','costela bovina','costela bovina assada']::text[], 373, 28.8, 0, 27.7, 150, 'porção', 'taco'),
  ('Cupim / fraldinha assada', array['cupim','fraldinha','churrasco','cupim / fraldinha assada']::text[], 330, 28, 0, 23.5, 150, 'porção', 'taco'),
  ('Carne de panela / músculo', array['acem','musculo','carne cozida','carne de panela','carne de panela / musculo']::text[], 194, 31.2, 0, 6.7, 120, 'porção', 'taco'),
  ('Fígado bovino grelhado', array['figado','figado bovino grelhado']::text[], 225, 29.9, 4.2, 9, 100, 'bife', 'taco'),
  ('Estrogonofe de frango', array['strogonoff','estrogonofe','estrogonofe de frango']::text[], 157, 17, 3, 8.5, 150, 'porção', 'taco'),
  ('Estrogonofe de carne', array['strogonoff de carne','estrogonofe de carne']::text[], 173, 15, 3.5, 11, 150, 'porção', 'taco'),
  ('Lombo de porco assado', array['porco','lombo','pernil','carne de porco','lombo de porco assado']::text[], 210, 32, 0, 8, 120, 'fatia', 'taco'),
  ('Bisteca de porco', array['bisteca','bisteca de porco']::text[], 311, 28.9, 0, 20.8, 120, 'unidade', 'taco'),
  ('Bacon frito', array['bacon','toucinho','bacon frito']::text[], 540, 37, 1.4, 42, 15, '2 fatias', 'taco'),
  ('Linguiça toscana assada', array['linguica','linguica toscana','linguica toscana assada']::text[], 296, 18, 0.5, 24, 70, 'gomo', 'taco'),
  ('Calabresa', array['calabresa']::text[], 320, 16, 3, 27, 50, 'porção', 'taco'),
  ('Salsicha', array['salsicha']::text[], 257, 11.6, 3.1, 22, 50, 'unidade', 'taco'),
  ('Presunto', array['presunto']::text[], 110, 17, 2, 4, 15, 'fatia', 'taco'),
  ('Peito de peru', array['blanquet','peito de peru']::text[], 100, 18, 2.4, 2, 15, 'fatia', 'taco'),
  ('Mortadela', array['mortadela']::text[], 269, 12, 5.8, 21.6, 15, 'fatia', 'taco'),
  ('Salame', array['salame']::text[], 398, 25.8, 2.9, 31, 10, 'fatia', 'taco'),
  ('Hambúrguer bovino (carne)', array['blend','burger','hamburguer de carne','hamburguer bovino (carne)']::text[], 250, 20, 1, 18, 120, 'unidade', 'taco'),
  ('Almôndega', array['almondega','almondegas']::text[], 200, 14, 8, 12, 30, 'unidade', 'taco'),
  ('Kibe assado', array['kibe assado','quibe assado']::text[], 180, 12, 15, 8, 100, 'pedaço', 'taco'),
  ('Tilápia grelhada', array['peixe','tilapia','pescada','merluza','file de peixe','tilapia grelhada']::text[], 128, 26.1, 0, 2.7, 120, 'filé', 'taco'),
  ('Salmão grelhado', array['salmao','salmao grelhado']::text[], 243, 26, 0, 14.6, 120, 'posta', 'taco'),
  ('Atum em água (lata)', array['atum','atum em agua (lata)']::text[], 116, 25.5, 0, 0.8, 80, 'lata drenada', 'taco'),
  ('Atum em óleo (lata)', array['atum em oleo','atum em oleo (lata)']::text[], 198, 26, 0, 10, 80, 'lata drenada', 'taco'),
  ('Sardinha em lata', array['sardinha','sardinha em lata']::text[], 208, 24, 0, 12, 80, 'lata drenada', 'taco'),
  ('Camarão cozido', array['camarao','camarao cozido']::text[], 90, 19, 0, 1, 100, 'porção', 'taco'),
  ('Bacalhau cozido', array['bacalhau','bacalhoada','bacalhau cozido']::text[], 136, 24, 0, 3.6, 120, 'porção', 'taco'),
  ('Ovo cozido', array['ovo','ovos','ovo cozido']::text[], 146, 13.3, 0.6, 9.5, 50, 'unidade', 'taco'),
  ('Ovo frito', array['ovo frito','ovos fritos']::text[], 240, 15.6, 1.2, 18.6, 50, 'unidade', 'taco'),
  ('Ovo mexido / omelete', array['omelete','ovo mexido','ovos mexidos','omelete simples','ovo mexido / omelete']::text[], 190, 12.5, 1.5, 15, 60, 'unidade', 'taco'),
  ('Clara de ovo', array['clara','claras','clara de ovo']::text[], 52, 10.9, 0.7, 0.2, 33, 'unidade', 'taco'),
  ('Leite integral', array['leite','leite integral']::text[], 61, 3.2, 4.7, 3.3, 200, 'copo', 'taco'),
  ('Leite desnatado', array['leite desnatado']::text[], 35, 3.4, 5, 0.1, 200, 'copo', 'taco'),
  ('Leite semidesnatado', array['leite semidesnatado']::text[], 46, 3.3, 4.8, 1.5, 200, 'copo', 'taco'),
  ('Leite em pó integral', array['ninho','leite em po','leite em po integral']::text[], 497, 25.4, 39.2, 26.9, 20, '2 colheres de sopa', 'taco'),
  ('Achocolatado em pó', array['toddy','nescau','achocolatado','achocolatado em po']::text[], 400, 4.2, 90, 2.2, 20, '2 colheres de sopa', 'taco'),
  ('Achocolatado pronto (caixinha)', array['toddynho','achocolatado de caixinha','achocolatado pronto (caixinha)']::text[], 83, 2.4, 13, 2.3, 200, 'caixinha', 'taco'),
  ('Iogurte natural integral', array['iogurte','iogurte natural','iogurte natural integral']::text[], 51, 4.1, 5.8, 3, 170, 'pote', 'taco'),
  ('Iogurte grego', array['grego','iogurte grego']::text[], 120, 5, 9, 7, 100, 'pote', 'taco'),
  ('Iogurte proteico', array['yopro','iogurte protein','iogurte proteico']::text[], 70, 10, 5, 0.8, 160, 'pote', 'taco'),
  ('Bebida láctea / iogurte de saquinho', array['bebida lactea','iogurte de saquinho','bebida lactea / iogurte de saquinho']::text[], 80, 2.5, 13, 2, 200, 'copo', 'taco'),
  ('Queijo muçarela', array['queijo','mucarela','mussarela','queijo mucarela']::text[], 330, 22.6, 3, 25.2, 20, 'fatia', 'taco'),
  ('Queijo minas frescal', array['minas','frescal','queijo minas','queijo branco','queijo minas frescal']::text[], 264, 17.4, 3.2, 20.2, 30, 'fatia', 'taco'),
  ('Queijo prato', array['queijo prato']::text[], 360, 22.7, 1.9, 29.1, 20, 'fatia', 'taco'),
  ('Queijo parmesão ralado', array['parmesao','queijo ralado','queijo parmesao ralado']::text[], 453, 35.6, 1.7, 33.5, 10, 'colher de sopa', 'taco'),
  ('Queijo coalho', array['coalho','queijo coalho']::text[], 330, 22, 2, 25, 40, 'espeto', 'taco'),
  ('Queijo cottage', array['cottage','queijo cottage']::text[], 98, 11, 3.4, 4.3, 50, '2 colheres de sopa', 'taco'),
  ('Ricota', array['ricota']::text[], 140, 12.6, 3.8, 8.1, 30, 'fatia', 'taco'),
  ('Requeijão cremoso', array['catupiry','requeijao','requeijao cremoso']::text[], 257, 9.6, 2.4, 23.4, 30, 'colher de sopa', 'taco'),
  ('Requeijão light', array['requeijao light']::text[], 180, 11, 4, 13, 30, 'colher de sopa', 'taco'),
  ('Cream cheese', array['cream cheese','philadelphia']::text[], 300, 6, 4, 29, 30, 'colher de sopa', 'taco'),
  ('Manteiga', array['manteiga']::text[], 726, 0.4, 0, 82.4, 10, 'ponta de faca', 'taco'),
  ('Margarina', array['qualy','doriana','margarina']::text[], 596, 0, 0, 67.4, 10, 'ponta de faca', 'taco'),
  ('Creme de leite', array['creme de leite']::text[], 221, 1.5, 4.5, 22.5, 15, 'colher de sopa', 'taco'),
  ('Leite condensado', array['leite condensado']::text[], 313, 7.7, 57, 6.7, 20, 'colher de sopa', 'taco'),
  ('Whey protein (concentrado)', array['whey','whey protein','proteina em po','whey protein (concentrado)']::text[], 390, 78, 8, 6, 30, 'scoop', 'taco'),
  ('Albumina', array['albumina']::text[], 370, 82, 5, 0, 30, 'scoop', 'taco'),
  ('Caseína', array['caseina']::text[], 360, 80, 6, 2, 30, 'scoop', 'taco'),
  ('Hipercalórico (massa)', array['mass','massa em po','hipercalorico','hipercalorico (massa)']::text[], 380, 13, 75, 3, 100, 'porção', 'taco'),
  ('Banana prata', array['banana','banana prata','banana nanica']::text[], 98, 1.3, 26, 0.1, 90, 'unidade', 'taco'),
  ('Maçã', array['maca']::text[], 56, 0.3, 15.2, 0, 130, 'unidade', 'taco'),
  ('Pera', array['pera']::text[], 53, 0.6, 14, 0.1, 150, 'unidade', 'taco'),
  ('Laranja', array['laranja']::text[], 46, 1, 11.5, 0.1, 150, 'unidade', 'taco'),
  ('Mexerica / tangerina', array['ponkan','mexerica','bergamota','tangerina','mexerica / tangerina']::text[], 38, 0.8, 9.6, 0.1, 130, 'unidade', 'taco'),
  ('Mamão papaia', array['mamao','papaia','mamao papaia']::text[], 40, 0.5, 10.4, 0.1, 150, 'meia unidade', 'taco'),
  ('Manga', array['manga']::text[], 64, 0.4, 16.7, 0.3, 150, 'unidade pequena', 'taco'),
  ('Abacaxi', array['abacaxi']::text[], 48, 0.9, 12.3, 0.1, 100, 'fatia', 'taco'),
  ('Melancia', array['melancia']::text[], 33, 0.9, 8.1, 0, 200, 'fatia', 'taco'),
  ('Melão', array['melao']::text[], 29, 0.7, 7.5, 0, 150, 'fatia', 'taco'),
  ('Uva', array['uva','uvas']::text[], 53, 0.7, 13.6, 0.2, 100, 'cacho pequeno', 'taco'),
  ('Morango', array['morango','morangos']::text[], 30, 0.9, 6.8, 0.3, 100, 'xícara', 'taco'),
  ('Abacate', array['abacate']::text[], 96, 1.2, 6, 8.4, 100, 'meia unidade pequena', 'taco'),
  ('Kiwi', array['kiwi']::text[], 51, 1.3, 11.5, 0.6, 76, 'unidade', 'taco'),
  ('Goiaba', array['goiaba']::text[], 54, 1.1, 13, 0.4, 170, 'unidade', 'taco'),
  ('Maracujá (polpa)', array['maracuja','maracuja (polpa)']::text[], 68, 2, 12.3, 2.1, 50, 'unidade', 'taco'),
  ('Pêssego', array['pessego']::text[], 36, 0.8, 9.3, 0, 110, 'unidade', 'taco'),
  ('Ameixa', array['ameixa']::text[], 53, 0.8, 13.9, 0, 50, 'unidade', 'taco'),
  ('Caqui', array['caqui']::text[], 71, 0.4, 19.3, 0.1, 150, 'unidade', 'taco'),
  ('Açaí na tigela (com xarope)', array['acai','acai na tigela (com xarope)']::text[], 110, 1, 21, 3, 300, 'tigela média', 'taco'),
  ('Açaí puro (polpa)', array['acai puro','polpa de acai','acai puro (polpa)']::text[], 58, 0.8, 6.2, 3.9, 100, 'pacote', 'taco'),
  ('Uva-passa', array['passas','uva-passa','uva passa']::text[], 299, 3.1, 79, 0.5, 20, 'colher de sopa', 'taco'),
  ('Tâmara', array['tamara']::text[], 280, 2.5, 75, 0.4, 8, 'unidade', 'taco'),
  ('Coco ralado', array['coco','coco ralado']::text[], 592, 5.7, 10.4, 60, 10, 'colher de sopa', 'taco'),
  ('Salada de frutas', array['salada de frutas']::text[], 60, 0.7, 15, 0.2, 200, 'taça', 'taco'),
  ('Salada verde (alface, rúcula, agrião)', array['rucula','salada','agriao','alface','folhas','salada verde','salada verde (alface, rucula, agriao)']::text[], 15, 1.3, 2.4, 0.2, 60, 'prato de sobremesa', 'taco'),
  ('Tomate', array['tomate']::text[], 15, 1.1, 3.1, 0.2, 80, 'unidade', 'taco'),
  ('Pepino', array['pepino']::text[], 10, 0.9, 2, 0, 80, 'meia unidade', 'taco'),
  ('Cenoura crua', array['cenoura','cenoura crua']::text[], 34, 1.3, 7.7, 0.2, 50, 'meia unidade', 'taco'),
  ('Brócolis cozido', array['brocolis','brocolis cozido']::text[], 25, 2.1, 4.4, 0.5, 100, 'porção', 'taco'),
  ('Couve-flor cozida', array['couve-flor','couve flor','couve-flor cozida']::text[], 19, 1.2, 3.9, 0.3, 100, 'porção', 'taco'),
  ('Couve refogada', array['couve','couve refogada']::text[], 90, 1.7, 8.7, 6.6, 50, 'porção', 'taco'),
  ('Abobrinha refogada', array['abobrinha','abobrinha refogada']::text[], 30, 1.1, 4, 1.2, 100, 'porção', 'taco'),
  ('Abóbora cozida', array['abobora','jerimum','moranga','abobora cozida']::text[], 30, 0.7, 7, 0.2, 100, 'porção', 'taco'),
  ('Chuchu cozido', array['chuchu','chuchu cozido']::text[], 19, 0.4, 4.8, 0, 100, 'porção', 'taco'),
  ('Vagem cozida', array['vagem','vagem cozida']::text[], 25, 1.5, 5.3, 0.2, 80, 'porção', 'taco'),
  ('Berinjela refogada', array['berinjela','berinjela refogada']::text[], 40, 1, 5, 2, 100, 'porção', 'taco'),
  ('Beterraba cozida', array['beterraba','beterraba cozida']::text[], 32, 1.3, 7.2, 0.1, 60, 'porção', 'taco'),
  ('Legumes cozidos (mix)', array['legumes','legumes cozidos','seleta de legumes','legumes cozidos (mix)']::text[], 35, 1.8, 6.5, 0.3, 100, 'porção', 'taco'),
  ('Repolho', array['repolho']::text[], 17, 0.9, 3.9, 0.1, 60, 'porção', 'taco'),
  ('Pimentão', array['pimentao']::text[], 21, 1, 4.9, 0.2, 40, 'meia unidade', 'taco'),
  ('Cebola', array['cebola']::text[], 39, 1.7, 8.9, 0.1, 30, 'porção', 'taco'),
  ('Quiabo refogado', array['quiabo','quiabo refogado']::text[], 45, 1.9, 6.4, 1.5, 80, 'porção', 'taco'),
  ('Maionese de batata (salada)', array['salpicao','maionese de batata','salada de maionese','maionese de batata (salada)']::text[], 190, 3, 13, 14, 150, 'porção', 'taco'),
  ('Vinagrete', array['vinagrete']::text[], 40, 0.8, 4, 2.5, 50, 'porção', 'taco'),
  ('Palmito', array['palmito']::text[], 23, 2, 4.3, 0.4, 50, 'porção', 'taco'),
  ('Cogumelo (champignon)', array['shimeji','shitake','cogumelo','champignon','cogumelo (champignon)']::text[], 25, 2.5, 3.5, 0.3, 50, 'porção', 'taco'),
  ('Azeite de oliva', array['azeite','azeite de oliva']::text[], 884, 0, 0, 100, 8, 'colher de sopa', 'taco'),
  ('Óleo de soja / cozinha', array['oleo','oleo de soja','oleo de soja / cozinha']::text[], 884, 0, 0, 100, 8, 'colher de sopa', 'taco'),
  ('Maionese', array['maionese']::text[], 680, 1, 1, 75, 12, 'colher de sopa', 'taco'),
  ('Maionese light', array['maionese light']::text[], 320, 1, 7, 32, 12, 'colher de sopa', 'taco'),
  ('Ketchup', array['catchup','ketchup']::text[], 100, 1.2, 24, 0.1, 15, 'colher de sopa', 'taco'),
  ('Mostarda', array['mostarda']::text[], 70, 4, 6, 3.5, 10, 'colher de chá', 'taco'),
  ('Molho de tomate', array['molho sugo','molho de tomate','extrato de tomate']::text[], 40, 1.3, 7, 1, 60, 'concha pequena', 'taco'),
  ('Molho shoyu', array['shoyu','molho shoyu']::text[], 60, 6, 8, 0, 15, 'colher de sopa', 'taco'),
  ('Pasta de amendoim', array['pasta de amendoim','manteiga de amendoim']::text[], 590, 25, 20, 49, 15, 'colher de sopa', 'taco'),
  ('Amendoim torrado', array['amendoim','amendoim torrado']::text[], 581, 27.2, 20.3, 43.9, 30, 'punhado', 'taco'),
  ('Castanha-do-pará', array['castanha-do-para','castanha do para']::text[], 643, 14.5, 15.1, 63.5, 4, 'unidade', 'taco'),
  ('Castanha de caju', array['caju','castanha de caju']::text[], 570, 18.5, 29.1, 46.3, 25, 'punhado', 'taco'),
  ('Amêndoas', array['amendoa','amendoas']::text[], 581, 18.6, 29.5, 47.3, 25, 'punhado', 'taco'),
  ('Nozes', array['noz','nozes']::text[], 620, 14, 18.4, 59.4, 25, 'punhado', 'taco'),
  ('Mix de castanhas', array['castanhas','mix de nuts','mix de castanhas']::text[], 600, 17, 22, 52, 30, 'punhado', 'taco'),
  ('Chia', array['chia']::text[], 486, 16.5, 42, 30.7, 10, 'colher de sopa', 'taco'),
  ('Linhaça', array['linhaca']::text[], 495, 14.1, 43.3, 32.3, 10, 'colher de sopa', 'taco'),
  ('Chocolate ao leite', array['chocolate','barra de chocolate','chocolate ao leite']::text[], 540, 7.2, 59.6, 30.3, 25, 'barrinha / 4 quadradinhos', 'taco'),
  ('Chocolate amargo 70%', array['chocolate 70','chocolate amargo','chocolate amargo 70%']::text[], 580, 8, 36, 43, 20, '4 quadradinhos', 'taco'),
  ('Bombom', array['bombom','serenata','ouro branco','sonho de valsa']::text[], 510, 5.5, 60, 27, 20, 'unidade', 'taco'),
  ('Brigadeiro', array['brigadeiro']::text[], 400, 4, 60, 16, 20, 'unidade', 'taco'),
  ('Beijinho', array['beijinho']::text[], 390, 4.5, 58, 15, 20, 'unidade', 'taco'),
  ('Pudim de leite', array['pudim','pudim de leite']::text[], 257, 6.3, 40, 7.6, 100, 'fatia', 'taco'),
  ('Mousse de chocolate / maracujá', array['mousse','mousse de chocolate / maracuja']::text[], 280, 4.5, 30, 16, 100, 'taça', 'taco'),
  ('Bolo simples', array['bolo','bolo de fuba','bolo simples','bolo de cenoura']::text[], 330, 5.5, 53, 11, 60, 'fatia', 'taco'),
  ('Bolo de chocolate com cobertura', array['bolo de chocolate','bolo de chocolate com cobertura']::text[], 410, 5, 55, 19, 80, 'fatia', 'taco'),
  ('Sorvete de massa', array['sorvete','sorvete de massa']::text[], 200, 3.5, 24, 10, 100, 'bola dupla', 'taco'),
  ('Picolé de fruta', array['picole','picole de fruta']::text[], 90, 0.5, 22, 0.2, 60, 'unidade', 'taco'),
  ('Açúcar', array['acucar']::text[], 387, 0, 99.5, 0, 5, 'colher de chá', 'taco'),
  ('Mel', array['mel']::text[], 309, 0.3, 84, 0, 15, 'colher de sopa', 'taco'),
  ('Doce de leite', array['doce de leite']::text[], 306, 5.5, 55, 6, 20, 'colher de sopa', 'taco'),
  ('Goiabada', array['goiabada']::text[], 269, 0.4, 74, 0.1, 30, 'fatia', 'taco'),
  ('Paçoca', array['pacoca']::text[], 500, 14, 52, 26, 20, 'unidade', 'taco'),
  ('Barra de cereal', array['barra de cereal','barrinha de cereal']::text[], 380, 5, 70, 9, 25, 'unidade', 'taco'),
  ('Barra de proteína', array['bold','protein bar','barra de proteina','barrinha de proteina']::text[], 360, 30, 35, 12, 50, 'unidade', 'taco'),
  ('Churros', array['churros']::text[], 390, 5, 50, 19, 60, 'unidade', 'taco'),
  ('Donut / rosquinha', array['donut','sonho','rosquinha','donut / rosquinha']::text[], 420, 5, 50, 22, 70, 'unidade', 'taco'),
  ('Gelatina pronta', array['gelatina','gelatina pronta']::text[], 60, 1.5, 14, 0, 120, 'pote', 'taco'),
  ('Coxinha', array['coxinha']::text[], 290, 9, 30, 15, 100, 'unidade média', 'taco'),
  ('Pastel frito', array['pastel','pastel frito']::text[], 320, 9, 30, 18, 90, 'unidade', 'taco'),
  ('Esfiha de carne', array['esfiha','esfirra','esfiha de carne']::text[], 290, 11, 38, 10, 80, 'unidade', 'taco'),
  ('Kibe frito', array['kibe','quibe','kibe frito']::text[], 290, 12, 25, 16, 90, 'unidade', 'taco'),
  ('Empada', array['empada','empadinha']::text[], 380, 8, 35, 23, 60, 'unidade', 'taco'),
  ('Enroladinho de salsicha', array['enroladinho','enroladinho de salsicha']::text[], 330, 9, 32, 18, 70, 'unidade', 'taco'),
  ('Pão de batata recheado', array['pao de batata','pao de batata recheado']::text[], 290, 8, 40, 11, 80, 'unidade', 'taco'),
  ('Pizza muçarela', array['pizza','pizza mucarela','pizza de queijo','pizza de mussarela']::text[], 270, 11, 30, 11, 110, 'fatia', 'taco'),
  ('Pizza calabresa', array['pizza calabresa','pizza de calabresa']::text[], 280, 12, 29, 13, 110, 'fatia', 'taco'),
  ('Hambúrguer de lanchonete (x-burguer)', array['lanche','whopper','big mac','x-salada','x-burguer','x burguer','hamburguer','hamburguer de lanchonete (x-burguer)']::text[], 250, 13, 24, 11, 220, 'unidade', 'taco'),
  ('X-tudo', array['x-tudo','x tudo','x bacon','x-bacon']::text[], 270, 13, 20, 16, 350, 'unidade', 'taco'),
  ('Cachorro-quente completo', array['dogao','hot dog','cachorro quente','cachorro-quente completo']::text[], 240, 9, 25, 11, 200, 'unidade', 'taco'),
  ('Misto quente', array['misto','misto quente']::text[], 290, 14, 30, 12, 120, 'unidade', 'taco'),
  ('Sanduíche natural', array['sanduiche','sanduiche natural']::text[], 210, 11, 25, 7, 150, 'unidade', 'taco'),
  ('Wrap de frango', array['wrap','burrito','tortilha','wrap de frango']::text[], 220, 13, 24, 8, 180, 'unidade', 'taco'),
  ('Tapioca recheada (queijo e presunto)', array['tapioca recheada','tapioca de queijo','tapioca recheada (queijo e presunto)']::text[], 240, 10, 32, 8, 150, 'unidade', 'taco'),
  ('Sushi / sashimi (média)', array['sushi','uramaki','sashimi','japones','niguiri','sushi / sashimi (media)']::text[], 150, 6, 25, 2.5, 30, 'peça', 'taco'),
  ('Hot roll', array['hot roll','hot philadelphia']::text[], 290, 7, 30, 15, 35, 'peça', 'taco'),
  ('Temaki de salmão', array['temaki','temaki de salmao']::text[], 170, 7, 22, 6, 180, 'unidade', 'taco'),
  ('Yakisoba', array['yakisoba']::text[], 140, 7, 18, 4.5, 350, 'prato', 'taco'),
  ('Parmegiana (frango/carne)', array['parmediana','parmegiana','a parmegiana','parmegiana (frango/carne)']::text[], 220, 17, 10, 12, 250, 'porção', 'taco'),
  ('Frango à milanesa', array['milanesa','a milanesa','frango a milanesa']::text[], 250, 20, 12, 13, 150, 'filé', 'taco'),
  ('Batata recheada', array['batata recheada']::text[], 150, 5, 18, 6, 350, 'unidade', 'taco'),
  ('Acarajé', array['acaraje']::text[], 300, 8, 25, 18, 150, 'unidade', 'taco'),
  ('Pão com ovo', array['pao com ovo']::text[], 250, 11, 29, 10, 110, 'unidade', 'taco'),
  ('Prato feito (PF: arroz, feijão, carne, salada)', array['pf','marmita','marmitex','prato feito','prato comercial','prato feito (pf: arroz, feijao, carne, salada)']::text[], 150, 8, 17, 5.5, 450, 'prato', 'taco'),
  ('Refrigerante comum', array['coca','refri','pepsi','fanta','sprite','guarana','coca cola','refrigerante','refrigerante comum']::text[], 42, 0, 10.6, 0, 350, 'lata', 'taco'),
  ('Refrigerante zero / diet', array['diet','zero','coca zero','guarana zero','refrigerante zero','refrigerante zero / diet']::text[], 1, 0, 0, 0, 350, 'lata', 'taco'),
  ('Suco de laranja natural', array['suco','suco natural','suco de laranja','suco de laranja natural']::text[], 45, 0.7, 10.4, 0.2, 250, 'copo', 'taco'),
  ('Suco de caixinha / néctar', array['nectar','del valle','suco de caixinha','suco industrializado','suco de caixinha / nectar']::text[], 55, 0.2, 13.5, 0, 250, 'copo', 'taco'),
  ('Suco em pó preparado', array['tang','clight','suco em po','suco em po preparado']::text[], 30, 0, 7.5, 0, 250, 'copo', 'taco'),
  ('Água de coco', array['agua de coco']::text[], 22, 0, 5.3, 0, 300, 'copo', 'taco'),
  ('Energético', array['monster','red bull','energetico']::text[], 45, 0, 11, 0, 250, 'lata', 'taco'),
  ('Isotônico', array['gatorade','powerade','isotonico']::text[], 24, 0, 6, 0, 500, 'garrafa', 'taco'),
  ('Cerveja', array['chopp','chope','breja','cerveja']::text[], 43, 0.5, 3.6, 0, 350, 'lata', 'taco'),
  ('Cerveja sem álcool', array['cerveja zero','cerveja sem alcool']::text[], 20, 0.3, 4.5, 0, 350, 'lata', 'taco'),
  ('Vinho tinto', array['vinho','vinho tinto','vinho branco']::text[], 85, 0.1, 2.6, 0, 150, 'taça', 'taco'),
  ('Caipirinha', array['caipirinha','caipiroska']::text[], 170, 0, 20, 0, 200, 'copo', 'taco'),
  ('Destilado (cachaça/vodka/whisky)', array['gin','dose','vodka','whisky','cachaca','destilado (cachaca/vodka/whisky)']::text[], 231, 0, 0, 0, 50, 'dose', 'taco'),
  ('Café sem açúcar', array['cafe','expresso','cafezinho','cafe preto','cafe sem acucar']::text[], 2, 0.1, 0, 0, 100, 'xícara', 'taco'),
  ('Café com açúcar', array['cafe adocado','cafe com acucar']::text[], 40, 0.3, 9.5, 0, 100, 'xícara', 'taco'),
  ('Café com leite', array['media','pingado','cafe com leite']::text[], 45, 2, 5, 1.8, 200, 'copo', 'taco'),
  ('Cappuccino', array['capuccino','cappuccino']::text[], 75, 3, 10, 2.5, 200, 'xícara grande', 'taco'),
  ('Chá sem açúcar', array['cha','mate','cha verde','chimarrao','cha sem acucar']::text[], 1, 0, 0.2, 0, 200, 'xícara', 'taco'),
  ('Vitamina de banana com leite', array['batida','vitamina','vitamina de banana','vitamina de banana com leite']::text[], 85, 3, 13, 2.5, 300, 'copo', 'taco'),
  ('Shake de whey com leite', array['shake','shake de whey','shake de whey com leite']::text[], 95, 9.5, 6, 3.5, 300, 'copo', 'taco'),
  ('Caldo de cana', array['garapa','caldo de cana']::text[], 70, 0, 18, 0, 300, 'copo', 'taco'),
  ('Sopa de legumes', array['sopa','caldo','sopa de legumes']::text[], 45, 2, 7, 1, 300, 'prato fundo', 'taco'),
  ('Canja de galinha', array['canja','canja de galinha']::text[], 60, 4.5, 7, 1.5, 300, 'prato fundo', 'taco'),
  ('Caldo verde', array['caldo verde']::text[], 75, 2.5, 7, 4, 300, 'prato fundo', 'taco'),
  ('Arroz carreteiro', array['carreteiro','arroz carreteiro']::text[], 170, 8, 20, 6, 250, 'porção', 'taco'),
  ('Galinhada', array['galinhada']::text[], 150, 9, 18, 4.5, 300, 'prato', 'taco'),
  ('Baião de dois', array['baiao','baiao de dois']::text[], 160, 7, 20, 5.5, 250, 'porção', 'taco'),
  ('Escondidinho de carne', array['escondidinho','escondidinho de carne']::text[], 140, 8, 12, 7, 300, 'porção', 'taco'),
  ('Moqueca de peixe', array['moqueca','moqueca de peixe']::text[], 120, 12, 3, 7, 250, 'porção', 'taco'),
  ('Risoto', array['risoto']::text[], 150, 4, 20, 5.5, 250, 'prato', 'taco'),
  ('Omelete recheado', array['omelete recheada','omelete recheado','omelete de queijo']::text[], 200, 13, 2, 15, 150, 'unidade', 'taco'),
  ('Polenta', array['angu','polenta']::text[], 70, 1.6, 15, 0.3, 150, 'porção', 'taco'),
  ('Polenta frita', array['polenta frita']::text[], 250, 3, 30, 13, 100, 'porção', 'taco')
on conflict (nome) do update set
  chaves = excluded.chaves, kcal = excluded.kcal, p = excluded.p, c = excluded.c, g = excluded.g,
  porcao = excluded.porcao, unidade = excluded.unidade, fonte = excluded.fonte;
